[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["npm install -g bun@1.3.6"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bunx serve dist -s -l 3000"
