// Solana integration layer for the Convex crank service
"use node";
import * as anchor from "@coral-xyz/anchor";
import { Connection, PublicKey, Keypair, Transaction, VersionedTransaction, ParsedTransactionWithMeta } from "@solana/web3.js";
import { GameConfig, GameRound, DOMIN8_PROGRAM_ID, PDA_SEEDS, BetInfoStruct } from "./types";
import { Buffer } from "buffer";
import bs58 from "bs58";

// Import the IDL type (this will be generated by Anchor)
import type { Domin8Prgm } from "../../target/types/domin8_prgm";
import IDL from "./domin8_prgm.json";

// Simple NodeWallet implementation for server-side use
class NodeWallet implements anchor.Wallet {
  constructor(readonly payer: Keypair) {}

  async signTransaction<T extends Transaction | VersionedTransaction>(tx: T): Promise<T> {
    if (tx instanceof Transaction) {
      tx.partialSign(this.payer);
    } else {
      // VersionedTransaction needs different signing
      tx.sign([this.payer]);
    }
    return tx;
  }

  async signAllTransactions<T extends Transaction | VersionedTransaction>(txs: T[]): Promise<T[]> {
    return txs.map((tx) => {
      if (tx instanceof Transaction) {
        tx.partialSign(this.payer);
      } else {
        tx.sign([this.payer]);
      }
      return tx;
    });
  }

  get publicKey(): PublicKey {
    return this.payer.publicKey;
  }
}

export class SolanaClient {
  private connection: Connection;
  private program: anchor.Program<Domin8Prgm>;
  private provider: anchor.AnchorProvider;
  private authority: Keypair;

  constructor(rpcEndpoint: string, authorityPrivateKey: string) {
    // Initialize connection
    this.connection = new Connection(rpcEndpoint, "confirmed");

    // Create authority keypair from private key
    // Support both JSON array and Base58 formats
    let privateKeyBytes: Uint8Array;

    try {
      const trimmed = authorityPrivateKey.trim();

      if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
        // JSON array format: "[1,2,3,...]"
        privateKeyBytes = new Uint8Array(JSON.parse(trimmed));
      } else {
        // Base58 format (standard Solana wallet export)
        privateKeyBytes = bs58.decode(trimmed);

        // Validate it's a valid Solana keypair (64 bytes)
        if (privateKeyBytes.length !== 64) {
          throw new Error(`Invalid key length: ${privateKeyBytes.length} bytes (expected 64)`);
        }
      }

      this.authority = Keypair.fromSecretKey(privateKeyBytes);
    } catch (error) {
      throw new Error(
        `Failed to parse CRANK_AUTHORITY_PRIVATE_KEY: ${error instanceof Error ? error.message : String(error)}\n` +
          `Supported formats: JSON array [1,2,3,...] or Base58 string (88 chars)\n` +
          `Received (first 50 chars): ${authorityPrivateKey.substring(0, 50)}...`
      );
    }

    // Create provider with NodeWallet
    this.provider = new anchor.AnchorProvider(this.connection, new NodeWallet(this.authority), {
      commitment: "confirmed",
    });

    // Initialize program with real IDL
    this.program = new anchor.Program<Domin8Prgm>(IDL as Domin8Prgm, this.provider);
  }

  // Get PDAs for the game accounts (risk-based architecture)
  private getPDAs(roundId?: number) {
    // Config PDA (global configuration)
    const [config] = PublicKey.findProgramAddressSync(
      [PDA_SEEDS.DOMIN8_CONFIG],
      DOMIN8_PROGRAM_ID
    );

    // Active game PDA (single PDA that always points to current game)
    const [activeGame] = PublicKey.findProgramAddressSync(
      [PDA_SEEDS.ACTIVE_GAME],
      DOMIN8_PROGRAM_ID
    );

    // Derive per-game PDA if roundId is provided (for historical lookups)
    let gameRound: PublicKey | undefined;
    if (roundId !== undefined) {
      const roundIdBuffer = Buffer.alloc(8);
      roundIdBuffer.writeBigUInt64LE(BigInt(roundId));
      [gameRound] = PublicKey.findProgramAddressSync(
        [PDA_SEEDS.DOMIN8_GAME, roundIdBuffer],
        DOMIN8_PROGRAM_ID
      );
    }

    return { config, activeGame, gameRound };
  }

  // Get current round ID from Domin8Config
  async getCurrentRoundId(): Promise<number> {
    const { config } = this.getPDAs();

    try {
      const account = await this.program.account.domin8Config.fetchNullable(config);

      if (!account) {
        console.warn("Config account doesn't exist yet");
        return 0;
      }

      return account.gameRound?.toNumber() ?? 0;
    } catch (error) {
      console.error("Error fetching config:", error);
      return 0;
    }
  }

  // Get current game configuration (risk-based architecture)
  async getGameConfig(): Promise<GameConfig | null> {
    const { config } = this.getPDAs();

    try {
      const account = await this.program.account.domin8Config.fetchNullable(config);

      if (!account) {
        console.warn("Config account doesn't exist yet");
        return null;
      }

      return {
        admin: account.admin?.toBase58() ?? "",
        treasury: account.treasury?.toBase58() ?? "",
        gameRound: account.gameRound?.toNumber() ?? 0,
        houseFee: account.houseFee?.toNumber() ?? 0,
        minDepositAmount: account.minDepositAmount?.toNumber() ?? 0,
        maxDepositAmount: account.maxDepositAmount?.toNumber() ?? 0,
        roundTime: account.roundTime?.toNumber() ?? 0,
        lock: account.lock ?? false,
        force: Array.from(account.force || []),
      };
    } catch (error) {
      console.error("Error fetching game config:", error);
      return null;
    }
  }

  // Get current game round state (risk-based architecture)
  async getGameRound(roundId?: number): Promise<GameRound | null> {
    // First get the current round ID if not provided
    const currentRoundId = roundId ?? (await this.getCurrentRoundId());
    console.log("---->Current round ID:", currentRoundId);

    // Derive the PDA for the current round
    const { gameRound } = this.getPDAs(currentRoundId);

    if (!gameRound) {
      throw new Error("Failed to derive game round PDA");
    }

    try {
      // Fetch account with null check
      const account = await this.program.account.domin8Game.fetchNullable(gameRound);

      // If account doesn't exist or was closed, try previous round
      if (!account) {
        console.log(`Game round ${currentRoundId} account doesn't exist or was closed`);

        // Try previous round if roundId > 0
        if (currentRoundId > 0) {
          console.log(`Attempting to fetch previous round ${currentRoundId - 1}`);
          return this.getGameRound(currentRoundId - 1);
        }
        // No more rounds to check
        return null;
      }

      console.log("=== Game Round Account ===");
      console.log(`  Game Round: ${account.gameRound?.toNumber()}`);
      console.log(`  Status: ${account.status} (0=open, 1=closed)`);
      console.log(`  Bet Count: ${account.bets?.length ?? 0}`);
      console.log(`  Total Deposit: ${account.totalDeposit?.toNumber()} lamports`);
      console.log(`  Winner: ${account.winner?.toBase58() ?? "None"}`);
      console.log(`  Winning Bet Index: ${account.winningBetIndex?.toNumber() ?? "N/A"}`);
      console.log("==========================");

      // Transform bets array
      const bets: BetInfoStruct[] = (account.bets || []).map((bet: any) => ({
        walletIndex: bet.walletIndex,
        amount: bet.amount?.toNumber() ?? 0,
        skin: bet.skin,
        position: [bet.position[0], bet.position[1]] as [number, number],
      }));

      return {
        gameRound: account.gameRound?.toNumber() ?? 0,
        startDate: account.startDate?.toNumber() ?? 0,
        endDate: account.endDate?.toNumber() ?? 0,
        totalDeposit: account.totalDeposit?.toNumber() ?? 0,
        rand: account.rand?.toString() ?? "0", // Convert to string to avoid overflow
        userCount: account.userCount?.toNumber() ?? 0,
        force: Array.from(account.force || []),
        status: account.status ?? 0,
        winner: account.winner ? account.winner.toBase58() : null,
        winnerPrize: account.winnerPrize?.toNumber() ?? 0,
        winningBetIndex: account.winningBetIndex ? account.winningBetIndex.toNumber() : null,
        wallets: (account.wallets || []).map((w: any) => w.toBase58()),
        bets,
        // Computed properties for backward compatibility
        roundId: account.gameRound?.toNumber() ?? 0,
        startTimestamp: account.startDate?.toNumber() ?? 0,
        endTimestamp: account.endDate?.toNumber() ?? 0,
        totalPot: account.totalDeposit?.toNumber() ?? 0,
        betCount: bets.length,
        betAmounts: bets.map(b => b.amount),
        betSkin: bets.map(b => b.skin),
        betPosition: bets.map(b => b.position),
      };
    } catch (error) {
      // Game round account doesn't exist yet (no bets placed)
      console.log("No game round exists yet for round", currentRoundId);
      console.log("Error details:", error);
      return null;
    }
  }

  /**
   * Get the current active game state (risk-based architecture)
   * This fetches from the active_game PDA (single source of truth for current game)
   * Use this instead of getGameRound() for real-time game state
   */
  async getActiveGame(): Promise<GameRound | null> {
    const { activeGame } = this.getPDAs();

    try {
      // Fetch account with null check
      const account = await this.program.account.domin8Game.fetchNullable(activeGame);

      if (!account) {
        console.log("No active game exists");
        return null;
      }

      console.log("=== Active Game Account ===");
      console.log(`  Game Round: ${account.gameRound?.toNumber()}`);
      console.log(`  Status: ${account.status} (0=open, 1=closed)`);
      console.log(`  Bet Count: ${account.bets?.length ?? 0}`);
      console.log(`  Total Deposit: ${account.totalDeposit?.toNumber()} lamports`);
      console.log(`  Winner: ${account.winner?.toBase58() ?? "None"}`);
      console.log(`  Winning Bet Index: ${account.winningBetIndex?.toNumber() ?? "N/A"}`);
      console.log("===========================");

      // Transform bets array
      const bets: BetInfoStruct[] = (account.bets || []).map((bet: any) => ({
        walletIndex: bet.walletIndex,
        amount: bet.amount?.toNumber() ?? 0,
        skin: bet.skin,
        position: [bet.position[0], bet.position[1]] as [number, number],
      }));

      return {
        gameRound: account.gameRound?.toNumber() ?? 0,
        startDate: account.startDate?.toNumber() ?? 0,
        endDate: account.endDate?.toNumber() ?? 0,
        totalDeposit: account.totalDeposit?.toNumber() ?? 0,
        rand: account.rand?.toString() ?? "0", // Convert to string to avoid overflow
        userCount: account.userCount?.toNumber() ?? 0,
        force: Array.from(account.force || []),
        status: account.status ?? 0,
        winner: account.winner ? account.winner.toBase58() : null,
        winnerPrize: account.winnerPrize?.toNumber() ?? 0,
        winningBetIndex: account.winningBetIndex ? account.winningBetIndex.toNumber() : null,
        wallets: (account.wallets || []).map((w: any) => w.toBase58()),
        bets,
        // Computed properties for backward compatibility
        roundId: account.gameRound?.toNumber() ?? 0,
        startTimestamp: account.startDate?.toNumber() ?? 0,
        endTimestamp: account.endDate?.toNumber() ?? 0,
        totalPot: account.totalDeposit?.toNumber() ?? 0,
        betCount: bets.length,
        betAmounts: bets.map(b => b.amount),
        betSkin: bets.map(b => b.skin),
        betPosition: bets.map(b => b.position),
      };
    } catch (error) {
      console.log("Error fetching active game:", error);
      return null;
    }
  }

  /**
   * Get the active_game PDA address
   * This is the single PDA that always points to the current game
   */
  getActiveGamePDA(): PublicKey {
    const { activeGame } = this.getPDAs();
    return activeGame;
  }

  // Get current Solana slot
  async getCurrentSlot(): Promise<number> {
    return await this.connection.getSlot("confirmed");
  }

  // End game and lock for winner selection (risk-based architecture)
  async endGame(roundId: number): Promise<string> {
    const { config, activeGame } = this.getPDAs();
    const { gameRound } = this.getPDAs(roundId);

    if (!gameRound) {
      throw new Error("Failed to derive game round PDA");
    }

    console.log(`Ending game for round ${roundId}`);

    // Fetch config to get treasury and force
    const configAccount = await this.program.account.domin8Config.fetch(config);

    // Fetch game to get the force seed
    const gameAccount = await this.program.account.domin8Game.fetch(gameRound);

    // Derive VRF randomness account using ORAO VRF program
    const ORAO_VRF_PROGRAM_ID = new PublicKey("VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y");
    const RANDOMNESS_ACCOUNT_SEED = Buffer.from("orao-vrf-randomness-request");

    // Convert force from number[] to Buffer
    const forceBuffer = Buffer.from(gameAccount.force);

    const [vrfRandomness] = PublicKey.findProgramAddressSync(
      [RANDOMNESS_ACCOUNT_SEED, forceBuffer],
      ORAO_VRF_PROGRAM_ID
    );

    const tx = await this.program.methods
      .endGame(new anchor.BN(roundId))
      .accounts({
        config,
        game: gameRound,
        activeGame,
        admin: this.authority.publicKey,
        treasury: configAccount.treasury,
        vrfRandomness,
        systemProgram: anchor.web3.SystemProgram.programId,
      } as any)
      .rpc();

    return tx;
  }

  // Send prize to winner (risk-based architecture)
  async sendPrizeWinner(roundId: number): Promise<string> {
    const { config } = this.getPDAs();
    const { gameRound } = this.getPDAs(roundId);

    if (!gameRound) {
      throw new Error("Failed to derive game round PDA");
    }

    // Fetch game to get winner
    const gameAccount = await this.program.account.domin8Game.fetch(gameRound);

    if (!gameAccount.winner) {
      throw new Error("No winner determined yet");
    }

    const winnerPubkey = gameAccount.winner;
    console.log(`Sending prize to winner ${winnerPubkey.toBase58()} for round ${roundId}`);
    console.log(`Prize amount: ${gameAccount.winnerPrize.toString()} lamports`);

    const tx = await this.program.methods
      .sendPrizeWinner(new anchor.BN(roundId))
      .accounts({
        config,
        game: gameRound,
        claimer: this.authority.publicKey,
        winner: winnerPubkey,
        systemProgram: anchor.web3.SystemProgram.programId,
      } as any)
      .rpc();

    return tx;
  }

  // Note: VRF functionality removed - risk architecture uses simpler randomness

  // Fetch all bets for a specific round (risk-based architecture - bets stored inline)
  async getBetsForRound(roundId: number): Promise<Array<BetInfoStruct & { wallet: string }>> {
    const bets: Array<BetInfoStruct & { wallet: string }> = [];

    // Get game round account
    const { gameRound } = this.getPDAs(roundId);
    if (!gameRound) return bets;

    try {
      const gameRoundAccount = await this.program.account.domin8Game.fetch(gameRound);
      const wallets = gameRoundAccount.wallets || [];
      const betStructs = gameRoundAccount.bets || [];

      // Transform inline bets to include wallet address
      for (const bet of betStructs) {
        const walletPubkey = wallets[bet.walletIndex];
        if (walletPubkey) {
          bets.push({
            walletIndex: bet.walletIndex,
            amount: bet.amount?.toNumber() ?? 0,
            skin: bet.skin,
            position: [bet.position[0], bet.position[1]] as [number, number],
            wallet: walletPubkey.toBase58(),
          });
        }
      }
    } catch (error) {
      console.error(`Error fetching bets for round ${roundId}:`, error);
    }

    return bets;
  }

  /**
   * Get transaction signatures for the domin8 program within a time range
   * Used for event-based bet capture
   */
  async getProgramSignatures(limit: number = 100, before?: string): Promise<string[]> {
    try {
      const signatures = await this.connection.getSignaturesForAddress(
        DOMIN8_PROGRAM_ID,
        {
          limit,
          before,
        },
        "confirmed"
      );

      return signatures.map(sig => sig.signature);
    } catch (error) {
      console.error("Error fetching program signatures:", error);
      return [];
    }
  }

  /**
   * Parse BetPlaced events from transaction logs
   * Returns bet data extracted from on-chain events
   */
  async parseBetPlacedEvents(signature: string): Promise<Array<{
    roundId: number;
    player: string;
    amount: number;
    betCount: number;
    totalPot: number;
    endTimestamp: number;
    isFirstBet: boolean;
    timestamp: number;
    betIndex: number;
  }>> {
    try {
      const tx = await this.connection.getTransaction(signature, {
        commitment: "confirmed",
        maxSupportedTransactionVersion: 0,
      });

      if (!tx || !tx.meta) {
        console.log(`Transaction ${signature} not found or has no metadata`);
        return [];
      }

      // Check if transaction succeeded
      if (tx.meta.err) {
        console.log(`Transaction ${signature} failed:`, tx.meta.err);
        return [];
      }

      const events: any[] = [];

      // Parse logs for BetPlaced events
      // Anchor events are emitted as: "Program data: <base64_encoded_event>"
      const logs = tx.meta.logMessages || [];

      for (const log of logs) {
        // Look for anchor event logs
        if (log.includes("Program data:")) {
          try {
            // Extract base64 data
            const dataMatch = log.match(/Program data: (.+)/);
            if (!dataMatch) continue;

            const data = Buffer.from(dataMatch[1], "base64");

            // Anchor events start with 8-byte discriminator
            // BetPlaced event discriminator is derived from "event:BetPlaced"
            const eventDiscriminator = data.slice(0, 8);

            // Decode the event using Anchor's event parser
            const eventData = this.program.coder.events.decode(data.toString("base64"));

            if (eventData && eventData.name === "BetPlaced") {
              events.push({
                roundId: eventData.data.roundId?.toNumber() ?? 0,
                player: eventData.data.player?.toBase58() ?? "",
                amount: eventData.data.amount?.toNumber() ?? 0,
                betCount: eventData.data.betCount ?? 0,
                totalPot: eventData.data.totalPot?.toNumber() ?? 0,
                endTimestamp: eventData.data.endTimestamp?.toNumber() ?? 0,
                isFirstBet: eventData.data.isFirstBet ?? false,
                timestamp: eventData.data.timestamp?.toNumber() ?? 0,
                betIndex: eventData.data.betIndex ?? 0,
              });
            }
          } catch (error) {
            // Not a BetPlaced event, skip
            continue;
          }
        }
      }

      return events;
    } catch (error) {
      console.error(`Error parsing transaction ${signature}:`, error);
      return [];
    }
  }

  /**
   * Get all BetPlaced events from recent transactions
   * This is more efficient than polling individual bet PDAs
   *
   * @param limit - Maximum number of transactions to fetch
   * @param untilSignature - Fetch transactions until this signature (exclusive) - for incremental fetching
   */
  async getAllRecentBetEvents(limit: number = 100, untilSignature?: string): Promise<Array<{
    signature: string;
    roundId: number;
    player: string;
    amount: number;
    betCount: number;
    totalPot: number;
    endTimestamp: number;
    isFirstBet: boolean;
    timestamp: number;
    betIndex: number;
    slot: number;
  }>> {
    try {
      // Get recent signatures, optionally starting from a specific signature
      const options: any = { limit };
      if (untilSignature) {
        options.until = untilSignature; // Fetch transactions until (not including) this signature
      }

      const signatureInfos = await this.connection.getSignaturesForAddress(
        DOMIN8_PROGRAM_ID,
        options,
        "confirmed"
      );

      const allEvents: any[] = [];

      // Parse each transaction for BetPlaced events
      for (const sigInfo of signatureInfos) {
        const events = await this.parseBetPlacedEvents(sigInfo.signature);

        for (const event of events) {
          allEvents.push({
            signature: sigInfo.signature,
            slot: sigInfo.slot,
            ...event,
          });
        }
      }

      console.log(`Found ${allEvents.length} BetPlaced events from ${signatureInfos.length} transactions`);
      return allEvents;
    } catch (error) {
      console.error("Error fetching recent bet events:", error);
      return [];
    }
  }

  // Note: VRF helper methods removed - VRF is now handled directly by the smart contract
  // via ORAO VRF integration in create_game instruction

  // Confirm transaction with retry logic
  async confirmTransaction(signature: string, maxRetries: number = 3): Promise<boolean> {
    let retries = 0;

    while (retries < maxRetries) {
      try {
        const result = await this.connection.confirmTransaction(signature, "confirmed");

        if (result.value.err) {
          console.error(`Transaction failed: ${signature}`, result.value.err);
          return false;
        }

        return true;
      } catch (error) {
        retries++;
        console.warn(
          `Transaction confirmation retry ${retries}/${maxRetries} for ${signature}:`,
          error
        );

        if (retries >= maxRetries) {
          console.error(
            `Transaction confirmation failed after ${maxRetries} retries: ${signature}`
          );
          return false;
        }

        // Wait before retry
        await new Promise((resolve) => setTimeout(resolve, 2000));
      }
    }

    return false;
  }

  // Health check - test connection and authority (risk-based architecture)
  async healthCheck(): Promise<{ healthy: boolean; message: string; slot?: number }> {
    try {
      // Test connection
      const slot = await this.getCurrentSlot();

      // Test authority balance
      const balance = await this.connection.getBalance(this.authority.publicKey);
      if (balance < 10_000_000) {
        // Less than 0.01 SOL
        return {
          healthy: false,
          message: `Authority balance too low: ${balance / 1e9} SOL`,
          slot,
        };
      }

      // Test if config account exists
      const { config } = this.getPDAs();
      await this.program.account.domin8Config.fetch(config);

      // Note: We don't check activeGame/gameRound here since they may not exist yet (no bets placed)

      return {
        healthy: true,
        message: "All systems healthy",
        slot,
      };
    } catch (error) {
      return {
        healthy: false,
        message: `Health check failed: ${error instanceof Error ? error.message : String(error)}`,
      };
    }
  }
}
